const ELEMENTS = [
  {"number":1,"symbol":"H","name":"Hydrogen","atomic_mass":"1","neutrons":0,"group":1,"period":1,"category":"nonmetal","summary":"Lightest element."},
  {"number":2,"symbol":"He","name":"Helium","atomic_mass":"4","neutrons":2,"group":18,"period":1,"category":"noble-gas","summary":"Inert noble gas."},
  {"number":3,"symbol":"Li","name":"Lithium","atomic_mass":"7","neutrons":4,"group":1,"period":2,"category":"alkali-metal","summary":"Soft, silvery-white metal."},
  {"number":4,"symbol":"Be","name":"Beryllium","atomic_mass":"9","neutrons":5,"group":2,"period":2,"category":"alkaline-earth","summary":"Hard, gray metal."},
  {"number":5,"symbol":"B","name":"Boron","atomic_mass":"11","neutrons":6,"group":13,"period":2,"category":"metalloid","summary":"Essential trace element in plants."},
  {"number":6,"symbol":"C","name":"Carbon","atomic_mass":"12","neutrons":6,"group":14,"period":2,"category":"nonmetal","summary":"Basis of organic life."},
  {"number":7,"symbol":"N","name":"Nitrogen","atomic_mass":"14","neutrons":7,"group":15,"period":2,"category":"nonmetal","summary":"Makes up most of Earth's atmosphere."},
  {"number":8,"symbol":"O","name":"Oxygen","atomic_mass":"16","neutrons":8,"group":16,"period":2,"category":"nonmetal","summary":"Supports respiration."},
  {"number":9,"symbol":"F","name":"Fluorine","atomic_mass":"19","neutrons":10,"group":17,"period":2,"category":"nonmetal","summary":"Highly reactive gas."},
  {"number":10,"symbol":"Ne","name":"Neon","atomic_mass":"20","neutrons":10,"group":18,"period":2,"category":"noble-gas","summary":"Used in lighting."},
  {"number":11,"symbol":"Na","name":"Sodium","atomic_mass":"23","neutrons":12,"group":1,"period":3,"category":"alkali-metal","summary":"Highly reactive metal."},
  {"number":12,"symbol":"Mg","name":"Magnesium","atomic_mass":"24","neutrons":12,"group":2,"period":3,"category":"alkaline-earth","summary":"Light metal used in alloys."},
  {"number":13,"symbol":"Al","name":"Aluminium","atomic_mass":"27","neutrons":14,"group":13,"period":3,"category":"post-transition-metal","summary":"Lightweight metal."},
  {"number":14,"symbol":"Si","name":"Silicon","atomic_mass":"28","neutrons":14,"group":14,"period":3,"category":"metalloid","summary":"Semiconductor material."},
  {"number":15,"symbol":"P","name":"Phosphorus","atomic_mass":"31","neutrons":16,"group":15,"period":3,"category":"nonmetal","summary":"Vital for DNA and bones."},
  {"number":16,"symbol":"S","name":"Sulfur","atomic_mass":"32","neutrons":16,"group":16,"period":3,"category":"nonmetal","summary":"Yellow solid used in fertilizers."},
  {"number":17,"symbol":"Cl","name":"Chlorine","atomic_mass":"35","neutrons":18,"group":17,"period":3,"category":"nonmetal","summary":"Used as disinfectant."},
  {"number":18,"symbol":"Ar","name":"Argon","atomic_mass":"40","neutrons":22,"group":18,"period":3,"category":"noble-gas","summary":"Inert gas."},
  {"number":19,"symbol":"K","name":"Potassium","atomic_mass":"39","neutrons":20,"group":1,"period":4,"category":"alkali-metal","summary":"Essential mineral for cells."},
  {"number":20,"symbol":"Ca","name":"Calcium","atomic_mass":"40","neutrons":20,"group":2,"period":4,"category":"alkaline-earth","summary":"Important for bones."},
  {"number":21,"symbol":"Sc","name":"Scandium","atomic_mass":"45","neutrons":24,"group":3,"period":4,"category":"transition-metal","summary":"Rare earth metal."},
  {"number":22,"symbol":"Ti","name":"Titanium","atomic_mass":"48","neutrons":26,"group":4,"period":4,"category":"transition-metal","summary":"Strong low-density metal."},
  {"number":23,"symbol":"V","name":"Vanadium","atomic_mass":"51","neutrons":28,"group":5,"period":4,"category":"transition-metal","summary":"Used in steel alloys."},
  {"number":24,"symbol":"Cr","name":"Chromium","atomic_mass":"52","neutrons":28,"group":6,"period":4,"category":"transition-metal","summary":"Used in plating."},
  {"number":25,"symbol":"Mn","name":"Manganese","atomic_mass":"55","neutrons":30,"group":7,"period":4,"category":"transition-metal","summary":"Important alloying element."},
  {"number":26,"symbol":"Fe","name":"Iron","atomic_mass":"56","neutrons":30,"group":8,"period":4,"category":"transition-metal","summary":"Abundant structural metal."},
  {"number":27,"symbol":"Co","name":"Cobalt","atomic_mass":"59","neutrons":32,"group":9,"period":4,"category":"transition-metal","summary":"Used in alloys and batteries."},
  {"number":28,"symbol":"Ni","name":"Nickel","atomic_mass":"59","neutrons":31,"group":10,"period":4,"category":"transition-metal","summary":"Used in stainless steel."},
  {"number":29,"symbol":"Cu","name":"Copper","atomic_mass":"63","neutrons":34,"group":11,"period":4,"category":"transition-metal","summary":"Excellent conductor."},
  {"number":30,"symbol":"Zn","name":"Zinc","atomic_mass":"65","neutrons":35,"group":12,"period":4,"category":"transition-metal","summary":"Used for galvanizing."},
  {"number":31,"symbol":"Ga","name":"Gallium","atomic_mass":"70","neutrons":39,"group":13,"period":4,"category":"post-transition-metal","summary":"Melts in the hand."},
  {"number":32,"symbol":"Ge","name":"Germanium","atomic_mass":"73","neutrons":41,"group":14,"period":4,"category":"metalloid","summary":"Semiconductor material."},
  {"number":33,"symbol":"As","name":"Arsenic","atomic_mass":"75","neutrons":42,"group":15,"period":4,"category":"metalloid","summary":"Toxic element."},
  {"number":34,"symbol":"Se","name":"Selenium","atomic_mass":"79","neutrons":45,"group":16,"period":4,"category":"nonmetal","summary":"Trace element."},
  {"number":35,"symbol":"Br","name":"Bromine","atomic_mass":"80","neutrons":45,"group":17,"period":4,"category":"nonmetal","summary":"Red-brown liquid."},
  {"number":36,"symbol":"Kr","name":"Krypton","atomic_mass":"84","neutrons":48,"group":18,"period":4,"category":"noble-gas","summary":"Used in lighting."},
  {"number":37,"symbol":"Rb","name":"Rubidium","atomic_mass":"85","neutrons":48,"group":1,"period":5,"category":"alkali-metal","summary":"Soft, highly reactive metal."},
  {"number":38,"symbol":"Sr","name":"Strontium","atomic_mass":"87","neutrons":49,"group":2,"period":5,"category":"alkaline-earth","summary":"Used in fireworks."},
  {"number":39,"symbol":"Y","name":"Yttrium","atomic_mass":"89","neutrons":50,"group":3,"period":5,"category":"transition-metal","summary":"Used in LEDs and superconductors."},
  {"number":40,"symbol":"Zr","name":"Zirconium","atomic_mass":"91","neutrons":51,"group":4,"period":5,"category":"transition-metal","summary":"Corrosion-resistant metal."},
  {"number":41,"symbol":"Nb","name":"Niobium","atomic_mass":"93","neutrons":52,"group":5,"period":5,"category":"transition-metal","summary":"Used in superconducting alloys."},
  {"number":42,"symbol":"Mo","name":"Molybdenum","atomic_mass":"96","neutrons":54,"group":6,"period":5,"category":"transition-metal","summary":"High-melting metal."},
  {"number":43,"symbol":"Tc","name":"Technetium","atomic_mass":"98","neutrons":55,"group":7,"period":5,"category":"transition-metal","summary":"Lightest radioactive element."},
  {"number":44,"symbol":"Ru","name":"Ruthenium","atomic_mass":"101","neutrons":57,"group":8,"period":5,"category":"transition-metal","summary":"Used in electronics."},
  {"number":45,"symbol":"Rh","name":"Rhodium","atomic_mass":"103","neutrons":58,"group":9,"period":5,"category":"transition-metal","summary":"Catalyst metal."},
  {"number":46,"symbol":"Pd","name":"Palladium","atomic_mass":"106","neutrons":60,"group":10,"period":5,"category":"transition-metal","summary":"Used in catalytic converters."},
  {"number":47,"symbol":"Ag","name":"Silver","atomic_mass":"108","neutrons":61,"group":11,"period":5,"category":"transition-metal","summary":"Excellent conductor and used in coins."},
  {"number":48,"symbol":"Cd","name":"Cadmium","atomic_mass":"112","neutrons":64,"group":12,"period":5,"category":"transition-metal","summary":"Used in batteries."},
  {"number":49,"symbol":"In","name":"Indium","atomic_mass":"115","neutrons":66,"group":13,"period":5,"category":"post-transition-metal","summary":"Used in LCDs."},
  {"number":50,"symbol":"Sn","name":"Tin","atomic_mass":"119","neutrons":69,"group":14,"period":5,"category":"post-transition-metal","summary":"Used for coatings and alloys."},
  {"number":51,"symbol":"Sb","name":"Antimony","atomic_mass":"122","neutrons":71,"group":15,"period":5,"category":"metalloid","summary":"Used in flame retardants."},
  {"number":52,"symbol":"Te","name":"Tellurium","atomic_mass":"128","neutrons":76,"group":16,"period":5,"category":"metalloid","summary":"Used in alloys and semiconductors."},
  {"number":53,"symbol":"I","name":"Iodine","atomic_mass":"127","neutrons":74,"group":17,"period":5,"category":"nonmetal","summary":"Essential for thyroid function."},
  {"number":54,"symbol":"Xe","name":"Xenon","atomic_mass":"131","neutrons":77,"group":18,"period":5,"category":"noble-gas","summary":"Used in lighting and anesthesia."},
  {"number":55,"symbol":"Cs","name":"Cesium","atomic_mass":"133","neutrons":78,"group":1,"period":6,"category":"alkali-metal","summary":"Used in atomic clocks."},
  {"number":56,"symbol":"Ba","name":"Barium","atomic_mass":"137","neutrons":81,"group":2,"period":6,"category":"alkaline-earth","summary":"Used in drilling fluids."},
  {"number":57,"symbol":"La","name":"Lanthanum","atomic_mass":"139","neutrons":82,"group":3,"period":6,"category":"lanthanoid","summary":"Start of lanthanides."},
  {"number":58,"symbol":"Ce","name":"Cerium","atomic_mass":"140","neutrons":82,"group":4,"period":6,"category":"lanthanoid","summary":"Most abundant lanthanide."},
  {"number":59,"symbol":"Pr","name":"Praseodymium","atomic_mass":"141","neutrons":82,"group":5,"period":6,"category":"lanthanoid","summary":"Used in magnets."},
  {"number":60,"symbol":"Nd","name":"Neodymium","atomic_mass":"144","neutrons":84,"group":6,"period":6,"category":"lanthanoid","summary":"Used in strong magnets."},
  {"number":61,"symbol":"Pm","name":"Promethium","atomic_mass":"145","neutrons":84,"group":7,"period":6,"category":"lanthanoid","summary":"Rare radioactive lanthanide."},
  {"number":62,"symbol":"Sm","name":"Samarium","atomic_mass":"150","neutrons":88,"group":8,"period":6,"category":"lanthanoid","summary":"Used in magnets and lasers."},
  {"number":63,"symbol":"Eu","name":"Europium","atomic_mass":"152","neutrons":89,"group":9,"period":6,"category":"lanthanoid","summary":"Used in phosphors."},
  {"number":64,"symbol":"Gd","name":"Gadolinium","atomic_mass":"157","neutrons":93,"group":10,"period":6,"category":"lanthanoid","summary":"Used in MRI contrast agents."},
  {"number":65,"symbol":"Tb","name":"Terbium","atomic_mass":"159","neutrons":94,"group":11,"period":6,"category":"lanthanoid","summary":"Used in solid-state devices."},
  {"number":66,"symbol":"Dy","name":"Dysprosium","atomic_mass":"164","neutrons":98,"group":12,"period":6,"category":"lanthanoid","summary":"High magnetic anisotropy."},
  {"number":67,"symbol":"Ho","name":"Holmium","atomic_mass":"165","neutrons":98,"group":13,"period":6,"category":"lanthanoid","summary":"Used in lasers."},
  {"number":68,"symbol":"Er","name":"Erbium","atomic_mass":"167","neutrons":99,"group":14,"period":6,"category":"lanthanoid","summary":"Used in fiber-optic amplifiers."},
  {"number":69,"symbol":"Tm","name":"Thulium","atomic_mass":"169","neutrons":100,"group":15,"period":6,"category":"lanthanoid","summary":"Rare, used in medical devices."},
  {"number":70,"symbol":"Yb","name":"Ytterbium","atomic_mass":"173","neutrons":103,"group":16,"period":6,"category":"lanthanoid","summary":"Used in atomic clocks."},
  {"number":71,"symbol":"Lu","name":"Lutetium","atomic_mass":"175","neutrons":104,"group":17,"period":6,"category":"lanthanoid","summary":"Dense rare earth metal."},
  {"number":72,"symbol":"Hf","name":"Hafnium","atomic_mass":"178","neutrons":106,"group":4,"period":6,"category":"transition-metal","summary":"Used in nuclear reactors."},
  {"number":73,"symbol":"Ta","name":"Tantalum","atomic_mass":"181","neutrons":108,"group":5,"period":6,"category":"transition-metal","summary":"Used in electronics capacitors."},
  {"number":74,"symbol":"W","name":"Tungsten","atomic_mass":"184","neutrons":110,"group":6,"period":6,"category":"transition-metal","summary":"Highest melting point metal."},
  {"number":75,"symbol":"Re","name":"Rhenium","atomic_mass":"186","neutrons":111,"group":7,"period":6,"category":"transition-metal","summary":"High melting and density."},
  {"number":76,"symbol":"Os","name":"Osmium","atomic_mass":"190","neutrons":114,"group":8,"period":6,"category":"transition-metal","summary":"Very dense metal."},
  {"number":77,"symbol":"Ir","name":"Iridium","atomic_mass":"192","neutrons":115,"group":9,"period":6,"category":"transition-metal","summary":"Extremely corrosion-resistant."},
  {"number":78,"symbol":"Pt","name":"Platinum","atomic_mass":"195","neutrons":117,"group":10,"period":6,"category":"transition-metal","summary":"Catalyst and jewelry metal."},
  {"number":79,"symbol":"Au","name":"Gold","atomic_mass":"197","neutrons":118,"group":11,"period":6,"category":"transition-metal","summary":"Highly inert and precious."},
  {"number":80,"symbol":"Hg","name":"Mercury","atomic_mass":"201","neutrons":121,"group":12,"period":6,"category":"transition-metal","summary":"Liquid metal at room temperature."},
  {"number":81,"symbol":"Tl","name":"Thallium","atomic_mass":"204","neutrons":123,"group":13,"period":6,"category":"post-transition-metal","summary":"Toxic metal."},
  {"number":82,"symbol":"Pb","name":"Lead","atomic_mass":"207","neutrons":125,"group":14,"period":6,"category":"post-transition-metal","summary":"Heavy, malleable metal."},
  {"number":83,"symbol":"Bi","name":"Bismuth","atomic_mass":"209","neutrons":126,"group":15,"period":6,"category":"post-transition-metal","summary":"Low-toxicity heavy metal."},
  {"number":84,"symbol":"Po","name":"Polonium","atomic_mass":"209","neutrons":125,"group":16,"period":6,"category":"post-transition-metal","summary":"Radioactive element."},
  {"number":85,"symbol":"At","name":"Astatine","atomic_mass":"210","neutrons":125,"group":17,"period":6,"category":"halogen","summary":"Rare radioactive halogen."},
  {"number":86,"symbol":"Rn","name":"Radon","atomic_mass":"222","neutrons":136,"group":18,"period":6,"category":"noble-gas","summary":"Radioactive noble gas."},
  {"number":87,"symbol":"Fr","name":"Francium","atomic_mass":"223","neutrons":136,"group":1,"period":7,"category":"alkali-metal","summary":"Highly radioactive alkali metal."},
  {"number":88,"symbol":"Ra","name":"Radium","atomic_mass":"226","neutrons":138,"group":2,"period":7,"category":"alkaline-earth","summary":"Radioactive alkaline earth."},
  {"number":89,"symbol":"Ac","name":"Actinium","atomic_mass":"227","neutrons":138,"group":3,"period":7,"category":"actinoid","summary":"Start of actinides."},
  {"number":90,"symbol":"Th","name":"Thorium","atomic_mass":"232","neutrons":142,"group":4,"period":7,"category":"actinoid","summary":"Radioactive metal used in reactors."},
  {"number":91,"symbol":"Pa","name":"Protactinium","atomic_mass":"231","neutrons":140,"group":5,"period":7,"category":"actinoid","summary":"Rare radioactive element."},
  {"number":92,"symbol":"U","name":"Uranium","atomic_mass":"238","neutrons":146,"group":6,"period":7,"category":"actinoid","summary":"Fuel for nuclear reactors."},
  {"number":93,"symbol":"Np","name":"Neptunium","atomic_mass":"237","neutrons":144,"group":7,"period":7,"category":"actinoid","summary":"Transuranic radioactive element."},
  {"number":94,"symbol":"Pu","name":"Plutonium","atomic_mass":"244","neutrons":150,"group":8,"period":7,"category":"actinoid","summary":"Used in nuclear weapons and reactors."},
  {"number":95,"symbol":"Am","name":"Americium","atomic_mass":"243","neutrons":148,"group":9,"period":7,"category":"actinoid","summary":"Used in smoke detectors."},
  {"number":96,"symbol":"Cm","name":"Curium","atomic_mass":"247","neutrons":151,"group":10,"period":7,"category":"actinoid","summary":"Produced in nuclear reactors."},
  {"number":97,"symbol":"Bk","name":"Berkelium","atomic_mass":"247","neutrons":150,"group":11,"period":7,"category":"actinoid","summary":"Synthetic radioactive element."},
  {"number":98,"symbol":"Cf","name":"Californium","atomic_mass":"251","neutrons":153,"group":12,"period":7,"category":"actinoid","summary":"Used as neutron source."},
  {"number":99,"symbol":"Es","name":"Einsteinium","atomic_mass":"252","neutrons":153,"group":13,"period":7,"category":"actinoid","summary":"Synthetic, highly radioactive."},
  {"number":100,"symbol":"Fm","name":"Fermium","atomic_mass":"257","neutrons":157,"group":14,"period":7,"category":"actinoid","summary":"Synthetic element."},
  {"number":101,"symbol":"Md","name":"Mendelevium","atomic_mass":"258","neutrons":157,"group":15,"period":7,"category":"actinoid","summary":"Synthetic element."},
  {"number":102,"symbol":"No","name":"Nobelium","atomic_mass":"259","neutrons":157,"group":16,"period":7,"category":"actinoid","summary":"Synthetic element."},
  {"number":103,"symbol":"Lr","name":"Lawrencium","atomic_mass":"262","neutrons":159,"group":17,"period":7,"category":"actinoid","summary":"Synthetic element."},
  {"number":104,"symbol":"Rf","name":"Rutherfordium","atomic_mass":"267","neutrons":163,"group":4,"period":7,"category":"transition-metal","summary":"Synthetic transactinide."},
  {"number":105,"symbol":"Db","name":"Dubnium","atomic_mass":"270","neutrons":165,"group":5,"period":7,"category":"transition-metal","summary":"Synthetic element."},
  {"number":106,"symbol":"Sg","name":"Seaborgium","atomic_mass":"271","neutrons":165,"group":6,"period":7,"category":"transition-metal","summary":"Synthetic element."},
  {"number":107,"symbol":"Bh","name":"Bohrium","atomic_mass":"270","neutrons":163,"group":7,"period":7,"category":"transition-metal","summary":"Synthetic element."},
  {"number":108,"symbol":"Hs","name":"Hassium","atomic_mass":"270","neutrons":162,"group":8,"period":7,"category":"transition-metal","summary":"Synthetic element."},
  {"number":109,"symbol":"Mt","name":"Meitnerium","atomic_mass":"276","neutrons":167,"group":9,"period":7,"category":"transition-metal","summary":"Synthetic element."},
  {"number":110,"symbol":"Ds","name":"Darmstadtium","atomic_mass":"281","neutrons":171,"group":10,"period":7,"category":"transition-metal","summary":"Synthetic element."},
  {"number":111,"symbol":"Rg","name":"Roentgenium","atomic_mass":"282","neutrons":171,"group":11,"period":7,"category":"transition-metal","summary":"Synthetic element."},
  {"number":112,"symbol":"Cn","name":"Copernicium","atomic_mass":"285","neutrons":173,"group":12,"period":7,"category":"transition-metal","summary":"Synthetic element."},
  {"number":113,"symbol":"Nh","name":"Nihonium","atomic_mass":"286","neutrons":173,"group":13,"period":7,"category":"post-transition-metal","summary":"Synthetic element."},
  {"number":114,"symbol":"Fl","name":"Flerovium","atomic_mass":"289","neutrons":175,"group":14,"period":7,"category":"post-transition-metal","summary":"Synthetic element."},
  {"number":115,"symbol":"Mc","name":"Moscovium","atomic_mass":"289","neutrons":174,"group":15,"period":7,"category":"post-transition-metal","summary":"Synthetic element."},
  {"number":116,"symbol":"Lv","name":"Livermorium","atomic_mass":"293","neutrons":177,"group":16,"period":7,"category":"post-transition-metal","summary":"Synthetic element."},
  {"number":117,"symbol":"Ts","name":"Tennessine","atomic_mass":"294","neutrons":177,"group":17,"period":7,"category":"halogen","summary":"Synthetic halogen."},
  {"number":118,"symbol":"Og","name":"Oganesson","atomic_mass":"294","neutrons":176,"group":18,"period":7,"category":"noble-gas","summary":"Synthetic noble gas."},
];
